# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: kubectl get pods --kubeconfig=.circleci/kube/cicd-config
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: kubectl exec nginx-deployment-574b87c764-c429r --kubeconfig=.circleci/kube/cicd-config -- date
orbs:
  kubernetes: circleci/kubernetes@0.11.2
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
